version: '3.8'
services:
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: java_to_dev_app_db
      PGDATA: /var/lib/postgresql/data/pgdata
  helpdesk-service:
    container_name: "helpdesk-lasalle-dores"
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - db
    build:
      dockerfile: .