spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/helpdesk-dores
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  jackson:
    default-property-inclusion: non_null
  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
jwt:
  secret: 06eb9d7a-d9a2-4ea9-8d7c-2f4c54dc7363
  expiration: 999999
