spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk-dores
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
jwt:
  secret: 06eb9d7a-d9a2-4ea9-8d7c-2f4c54dc7363
  expiration: 999999